server:
   port: 8000

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/achievement_counter?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maxLifetime: 1800000