server:
   port: 8000

db:
 host: localhost:3306
 schema: achievement_counter
 username: root
 password: 1234
 url: jdbc:mysql://${db.host}/${db.schema}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  main:
    allow-bean-definition-overriding: true